Upgrade acts_as_list to 0.7.2
Fixes #3501

Fixes loading MiqCimDerivedMetric on rails 4.2.x and has probably been broken
since we upgraded from rails 3.2, maybe earlier:

```
irb(main):001:0> MiqCimDerivedMetric
NameError: undefined local variable or method `accessible_attributes' for #<Class:0x007ff34df30820>
  from /Users/joerafaniello/.gem/ruby/2.2.4/gems/acts_as_list-0.1.9/lib/acts_as_list/active_record/acts/list.rb:61:in `class_eval'
```

It appears that we only use acts_as_list to define a scope in MiqCimDerivedMetric:
`acts_as_list  :scope => :miq_storage_metric`

I'd rather just remove this dependency but I have no idea what to test after
removing it.