Migrator class was refactored in 5.2, use new api
The current_version and needs_migration? methods were moved in:
https://github.com/rails/rails/commit/a2827ec9811b5012e8e366011fd44c8eb53fc714

Related:
https://github.com/ManageIQ/manageiq-schema/commit/b53bf99eaabe4a472525ed17436b8845d6b935ed

Fixes:

  41) EvmApplication.deployment_status returns redeployment otherwise
      Failure/Error: return "upgrade"        if ActiveRecord::Migrator.needs_migration?

      NoMethodError:
        undefined method `needs_migration?' for ActiveRecord::Migrator:Class
      # ./lib/tasks/evm_application.rb:207:in `deployment_status'
      # ./spec/lib/tasks/evm_application_spec.rb:352:in `block (3 levels) in <top (required)>'